"%dev":
  quarkus:
    http:
      port: ${APP_PORT}
    datasource:
      db-kind: ${DB_SOURCE}
      jdbc:
        max-size: ${DB_POOL_MAX}
        min-size: ${DB_POOL_MIN}
        url: {DB_URL}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
    mailer:
      mock: ${EMAIL_MOCK}
      from: ${EMAIL_FROM}
      host: ${EMAIL_HOST}
      port: ${EMAIL_PORT}
      username: ${EMAIL_USER}
      password: ${EMAIL_PASSWORD}
"%lambda":
  quarkus:
    http:
      port: ${LAMBDA_HTTP_PORT}

#    datasource:
#       devservices:
#         enabled: false //para que en prod no levante docker
#      jdbc:
#        url: ${ORACLE_JDBC_URL}
#      username: ${ORACLE_USER}
#      password: ${ORACLE_PASS}
